<TitlePage>:
	canvas:
		Rectangle:
			pos: self.pos
			size: self.size
			source: "Poker2.jpg"

<LoginPage>
	canvas:
		Rectangle:
			pos: self.pos
			size: self.size
			source: "Poker2.jpg"
	Label:
		center_x: root.width/2
		top: root.top/2 + 100
		text: "Enter Your Name"
		font_size: 34

<PlayGame>
	canvas:
		Rectangle:
			pos: self.pos
			size: self.size
			source: "Table.png"
        	